# Databricks notebook source
# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS llm.rag.docs_text (id BIGINT GENERATED BY DEFAULT AS IDENTITY, text STRING) tblproperties ('delta.enableChangeDataFeed' = true);

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS llm.rag.docs_track (file_name STRING) tblproperties ('delta.enableChangeDataFeed' = true);

# COMMAND ----------

# MAGIC %md
# MAGIC The code tracks the row level changes.
